import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/provider/ClientProvider";
import { Toaster } from "@/components/ui/sonner"
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className={inter.className}>
          <NextTopLoader color="#F7E7DC" showSpinner={false} />
          {children}
          <Toaster richColors />
        </body>
      </ClientProvider>
    </html>
  );
}
